### PR TITLE
Fix typo 'acceptible'

### PR DESCRIPTION
**Pull request by TheTypoMaster**
Hi! I'm a bot that checks GitHub for spelling mistakes, and I found one in your repository. When it
should be 'acceptable', you typed 'acceptible'. I created this pull request to fix it!

If you think there is anything wrong with this pull request or just have a question, be kind to mail me 
at thetypomaster@hotmail.com (professional email, huh?). I’ll try to address the problem as soon as
I’m aware of it.

Looking for the source code of this bot? Well, you have to be patient! The bot is under development
and I will publish the source code as soon as I’m finished with it.

If you decide to close this pull request, pleace specify why before doing so.

With kind regards,
TheTypoMaster

### CODE REVIEW

**Comment by TheTypoMaster** [comment]
You may see why this is wrong, haha. Doing some new replacement code!

**Comment by gagin** [comment]
Oh, I missed the comment.

**Comment by auscompgeek** [comment]
This is why you _never_ blindly merge pull requests, ever.

**Comment by gagin** [comment]
Well, if it was about something serious - sure, I would be more cautious. But these were just my work notes, so it doesn't matter. Still a good lesson, you're right.

**Pull request merged**
